name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          make install

      - name: Run linter
        run: make lint


  publish:
    name: Building and publishing
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - uses: actions/checkout@v2

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Configure poetry
        run: poetry config virtualenvs.in-project true

      - name: Build a package
        run: make build

      - name: Install Dependencies
        run: make install

      - name: Fake publish (Real is not possible due to requirement to packege name)
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config http-basic.testpypi __token__ ${{ secrets.TEST_PYPI_API_TOKEN }}
          make publish --dry-run